### PR TITLE
Convert native hash

### PR DESCRIPTION
**Pull request by n0ts**
Before
```
      AWS__CloudFormation__Init do
        config do
          packages do
            yum(
              {"httpd"=>[]})
            end
        end
      end
```

After

```
      AWS__CloudFormation__Init do
        config do
          packages do
            yum(
              {"httpd"=>[]}
            )
            end
        end
      end
```

### CODE REVIEW

**Comment by winebarrel** [comment]
How about using `Object#pretty_inspect`?
https://docs.ruby-lang.org/ja/latest/method/Object/i/pretty_inspect.html

**Comment by n0ts** [comment]
@winebarrel 

Thanks, pretty_inspect is not included newline....
why...?

```
irb(main):014:0> require 'pp'
=> false
irb(main):015:0> puts ({ 'hoge' => 'bar', 'foo' => 'bar' }).pretty_inspect
{"hoge"=>"bar", "foo"=>"bar"}
=> nil
irb(main):016:0>
```

**Comment by n0ts** [comment]
@winebarrel Thanks, I update hash code style. Could you review it?
https://github.com/cookpad/styleguide/blob/master/ruby.en.md

**Review by winebarrel — APPROVED** [review]
I'm sorry to reply late...
LGTM

**Pull request merged**
